apiVersion: apimanagement.azure.com/v1api20240501
kind: Service
metadata:
  name: {{ .Values.apim.name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-gateway.labels" . | nindent 4 }}
spec:
  azureName: {{ .Values.apim.name | quote }}
  location: {{ .Values.apim.location | quote }}
  owner:
    name: {{ include "ai-gateway.resourceGroupName" . | quote }}
  publisherEmail: {{ .Values.apim.publisherEmail | quote }}
  publisherName: {{ .Values.apim.publisherName | quote }}
  sku:
    name: {{ .Values.apim.sku.name | quote }}
    capacity: {{ .Values.apim.sku.capacity }}
